"""Configuration package."""

from config.settings import (
    PROJECT_ROOT,
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    ARTIFACTS_DIR,
    UPLOADS_DIR,
    DATASET_COLUMN_MAPPING,
    DEFAULT_JOB_CSV,
    CLEANED_CSV,
    CLEANED_PARQUET,
    TFIDF_VECTORIZER_PKL,
    JOB_EMBEDDINGS_PKL,
    JOB_METADATA_PKL,
    SUPPORTED_RESUME_EXTENSIONS,
    TOP_N_MATCHES,
)
